[workspace]
members = [
    "./mini-agent",
    "./mini-agent-core",
    "./mini-agent-sink-prelude",
    "./mini-agent-source-prelude",
    "./mini-agent-source-sysinfo",
    "./mini-agent-source-timer",
]
resolver = "2"
