#!/bin/sh
set -e

# Add mini-agent to adm group to read /var/logs
usermod --append --groups adm mini-agent || true

if getent group 'systemd-journal'
then
  # Add mini-agent to systemd-journal to read journald logs
  usermod --append --groups systemd-journal mini-agent || true
  systemctl daemon-reload || true
fi

if getent group 'systemd-journal-remote'
then
  # Add mini-agent to systemd-journal-remote to read remote journald logs
  usermod --append --groups systemd-journal-remote mini-agent || true
  systemctl daemon-reload || true
fi

#DEBHELPER#